USE quiz;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(25) NOT NULL,
    password VARCHAR(72) NOT NULL,
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    rights ENUM('admin', 'user')
);

CREATE TABLE IF NOT EXISTS questions (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    topic INT NOT NULL,
    question VARCHAR(1024) NOT NULL
);

CREATE TABLE topics (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS high_scores (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(25) NOT NULL,
    topic_id INT NOT NULL,
    score INT NOT NULL,
    total_questions INT NOT NULL,
    completed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE CASCADE
);