USE quiz;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(25) NOT NULL,
    password VARCHAR(72) NOT NULL,
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    rights ENUM('admin', 'user')
);

CREATE TABLE IF NOT EXISTS questions (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    topic INT NOT NULL,
    question VARCHAR(1024) NOT NULL
);

CREATE TABLE topics (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64)
);